### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by noraj** [xire28/brute_force#1]
First thanks for this great project.

filter works by providing a regex ? But this seems to take the same time with or without filter, just that with a filter, filtered output are not tried. I don't know if there is a way to make it faster.

**Comment by xire28** [comment]
Hello, thanks !

The strings are generated by incrementing a counter (base 10) into the letters base (base N). It's one of the most simple implementation for a bruteforce generator.

Because of the simplicity, it has couple limitations, the filtering performance is one of them. Can't think of any way to change that without a full rewrite.

**Comment by noraj** [comment]
Ok but so filter are useless if they do not improve the performance ?

**Comment by xire28** [comment]
They are not if you want to generate a dictionnary words file for later use or blacklist specific patterns.
If you have a simple way to implement them in an optimized way, feel free to contribute.
